abide updates for raw to stage 0

diff --git a/utilities/contrib/abide/cascade_raw_to_0.sh.template b/utilities/contrib/abide/cascade_raw_to_0.sh.template
--- a/utilities/contrib/abide/cascade_raw_to_0.sh.template
+++ b/utilities/contrib/abide/cascade_raw_to_0.sh.template
@@ -2,71 +2,86 @@
 #SBATCH --time=1:00:00
 #SBATCH --account=def-jlevman
 # Account can be overridden with env variable SBATCH_ACCOUNT
-
 #SBATCH --cpus-per-task=1
-
 ##SBATCH --mail-type=ALL
 #SBATCH --mem-per-cpu=1000M
 #SBATCH -e PATIENT_RAW_0_%x-%j.err
 #SBATCH -o PATIENT_RAW_0_%x-%j.out
 
-module load StdEnv/2020
-module load gcc/9.3.0
-module load cuda/11.0
-module load fsl/6.0.3
-module load freesurfer
-module load gsl/2.6
-module load python/3.8.2
-
-. ${FSLDIR}/etc/fslconf/fsl.sh
 
 util=$CRUSH_PATH/utilities/contrib/abide
 patientID=PATIENT_RAW_0
 
 SUBJECTS_DIR=$CRUSH_DATASET_ROOT/abide/dataset/rawdata/stage_0
 
-############
-
-rsync -r $CRUSH_DATASET_ROOT/abide/dataset/source/$patientID $SUBJECTS_DIR
-cd $SUBJECTS_DIR
-
 subject=$patientID
 subjectescaped="${subject//_}"
 
-cd $SUBJECTS_DIR
+SOURCE_DIR=$CRUSH_DATASET_ROOT/abide/dataset/source/$subject
+
+cd $SOURCE_DIR
+session=$(ls |grep session_|cut -d\_ -f2)
+
+if [[ ! -d "${SOURCE_DIR}/session_${session}/anat_1" || ! -d "${SOURCE_DIR}/session_${session}/dti_1" ]];then
+    echo "Source incomplete.  missing anat_1 or dti_1.  Cannot continue this subject"
+fi
+
+echo "Found T1 in anat_1 and dwi in dti_1.  Source is complete"
+mkdir -p $SUBJECTS_DIR/sub-$subject/ses-$session/original/anat
+mkdir -p $SUBJECTS_DIR/sub-$subject/ses-$session/original/dwi
+#Get T1 image
+cp ${SOURCE_DIR}/session_${session}/anat_1/anat.nii.gz $SUBJECTS_DIR/sub-$subject/ses-$session/original/anat
+if [[ $? -ne 0 ]] ; then
+    echo "Failed to copy source anat.nii.gz to target"
+fi
+#Get diffusion image
+cp ${SOURCE_DIR}/session_${session}/dti_1/dti.nii.gz $SUBJECTS_DIR/sub-$subject/ses-$session/original/dwi
+if [[ $? -ne 0 ]] ; then
+    echo "Failed to copy source dti.nii.gz to target"
+fi
+cp ${SOURCE_DIR}/session_${session}/dti_fieldmap/dti.bvals $SUBJECTS_DIR/sub-$subject/ses-$session/original/dwi/bvals
+if [[ $? -ne 0 ]] ; then
+    echo "Failed to copy source dti.bvals to target"
+fi   
+cp ${SOURCE_DIR}/session_${session}/dti_fieldmap/dti.bvecs_image $SUBJECTS_DIR/sub-$subject/ses-$session/original/dwi/bvecs
+if [[ $? -ne 0 ]] ; then
+    echo "Failed to copy source dti.bvecs_image to target"
+fi  
+
+cd $SUBJECTS_DIR/sub-$subject/ses-$session/original/anat
+gunzip -f anat.nii.gz
+if [[ $? -ne 0 ]] ; then
+    echo "Unable to uncompress anat.nii.gz"
+else    
+    mv anat.nii sub-${subject}_ses-${session}_T1w.nii
+fi 
+
+cd $SUBJECTS_DIR/sub-$subject/ses-$session/original/dwi
+gunzip -f dti.nii.gz
+if [[ $? -ne 0 ]] ; then
+    echo "Unable to uncompress dti.nii.gz"
+else    
+    mv dti.nii sub-${subject}_ses-${session}_dwi.nii
+fi 
 
 
-################################################################################
-# TODO Moves necessary for the specified subject identified in variable patientID:
-# #example case: abide/dataset/source/29177/session_1
-# mkdir -p abide/dataset/rawdata/sub-29177/ses-1
-# for 29177/session_1 
-#     /anat_1  
-#         mkdir -p abide/dataset/rawdata/sub-29177/ses-1/original/anat
-#         gunzip and copy /anat_1/anat.nii.gz to rawdata/sub-29177/ses-1/original/sub-29177_ses-1-T1w.nii
-#     /dti_1
-#         mkdir -p abide/dataset/rawdata/sub-29177/ses-1/original/dwi 
-#         copy dti_1/dti.nii.gz to rawdata/sub-29177/ses-1/original/dwi/data.nii.gz
-#     /dti_fieldmap
-#         copy dti.bvals to rawdata/sub-29177/ses-1/original/dwi/bvals
-#         copy dti.bvecs to rawdata/sub-29177/ses-1/original/dwi/bvecs
 #  if success, move forward
 ################################################################################
 
    #    ############ The code below moves to the next step
 
-   #    echo "RAW to STAGE 0 COMPLETE.  ADVANCING FORWARD"
-   #    #MOVE FORWARD
-   #    cd $util
+echo "RAW to STAGE 0 COMPLETE.  ADVANCING FORWARD"
+#MOVE FORWARD
+cd $util
 
-   #    cat $util/cascade_recon_0.sh.template | sed -e "s/PATIENT_RECON_0/$subjectescaped/" |sed -e "s/SESSION_RECON_0/$suffixbsession/" > ~/jobs/generated/$subjectescaped-$suffixbsession-recon_0.sh
-   #    chmod u+x ~/jobs/generated/$subjectescaped-$suffixbsession-recon_0.sh
-   #    mkdir -p ~/jobs/generated/logs
-   #    cd ~/jobs/generated/logs
-   #    ############
-   #    mkdir -p ../completed
-   #    mv ../$patientID-raw_0.sh ../completed   #Move the currently running script to archive
-   #   ##UNCOMMENT THIS WHEN READY sbatch ~/jobs/generated/$subjectescaped-$suffixbsession-recon_0.sh
+cat $util/cascade_recon_0.sh.template | sed -e "s/PATIENT_RECON_0/$subjecte/" |sed -e "s/SESSION_RECON_0/$session/" > ~/jobs/generated/$subject-$session-recon_0.sh
+chmod u+x ~/jobs/generated/$subject-$session-recon_0.sh
+mkdir -p ~/jobs/generated/logs
+cd ~/jobs/generated/logs
+############
+mkdir -p ../completed
+mv ../$patientID-raw_0.sh ../completed   #Move the currently running script to archive
+sbatch ~/jobs/generated/$subject-$session-recon_0.sh
 
 
 cd $util
